### ISSUE TITLE
敢问数据源从哪儿来，到哪儿去？

### ISSUE THREAD

**Issue by yangyiRunning** [Rukey7/MvpApp#11]
UP主你好，因为看到你的项目是新闻阅读类、图片类的项目，因此想向你了解一下：

1.你的数据源是从哪里来的？？爬虫扒的 or 其他？
2.针对下载使用者的数据操作，最终保存到哪了？？是自编后端业务代码 or 用第三方的云存储服务 or 其他？

希望得到解答，先谢。

**Comment by Rukey7** [comment]
数据用Fiddler这个工具看它的Api接口，不够有些接口的使用参数可能不完整，这个项目没有后端，数据保存本地数据库
