### ISSUE TITLE
Failed to sync Gradle project 'MvpApp'

### ISSUE THREAD

**Issue by passXu** [Rukey7/MvpApp#15]
Required by:
    MvpApp:app:unspecified
    MvpApp:app:unspecified > com.github.Rukey7:TagLayout:1.0.3
    MvpApp:app:unspecified > MvpApp:RecyclerViewHelper:unspecified
    MvpApp:app:unspecified > MvpApp:downloaderLib:unspecified
    MvpApp:app:unspecified > MvpApp:playerview:unspecified
    MvpApp:app:unspecified > MvpApp:tinkerLib:unspecified

Please install the Android Support Repository from the Android SDK Manager.
<a href="openAndroidSdkManager">Open Android SDK Manager</a>

好像是没有指定远程仓库，或者指定错了，仓库里找不到依赖的工程，求解。已经安装过了 Android Support Repository

**Comment by Rukey7** [comment]
![image](https://cloud.githubusercontent.com/assets/13436901/23851034/dbe97ac6-081c-11e7-94c9-a75151d78b95.png)

仓库应该都指定了，你看是不是支持包或编译工具没下
