### ISSUE TITLE
播放视频时点击后应用直接奔溃了，好像是说少了个so库

### ISSUE THREAD

**Issue by xiemobiao** [Rukey7/MvpApp#18]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.dl7.mvp-1/base.apk", zip file "/data/app/com.dl7.mvp-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.dl7.mvp-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.dl7.mvp-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.dl7.mvp-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.dl7.mvp-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.dl7.mvp-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.dl7.mvp-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.dl7.mvp-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.dl7.mvp-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.dl7.mvp-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.dl7.mvp-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.dl7.mvp-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libijkffmpeg.so"

**Comment by Rukey7** [comment]
你找下之前的issue，这个问题提了好几次了。[](https://github.com/Rukey7/MvpApp/issues/6)

**Comment by Rukey7** [comment]
你找下之前issue，这问题提了好几次了。https://github.com/Rukey7/MvpApp/issues/6
