### ISSUE TITLE
新闻403

### ISSUE THREAD

**Issue by quert999** [Rukey7/MvpApp#19]
在新闻列表不断下拉刷新，有时会出现服务器403状态。
这时点击空白处可以进入详情。

**Comment by Rukey7** [comment]
我之前有改过刷新问题，你更新代码看看，如果出现403的问题不用在意，因为我调的不是规范的接口，参数可能有遗漏

**Comment by quert999** [comment]
在显示网络异常，点击重试的时候，没有屏蔽空白处的点击事件，还是可以进入详情

**Comment by Rukey7** [comment]
嗯，之前是有这个问题的，应该是改了
