### ISSUE TITLE
android 7.0 HUAWEI MHA-AL00 视频播放crash

### ISSUE THREAD

**Issue by JoshuaJanJ** [Rukey7/MvpApp#2]

**Comment by Rukey7** [comment]
7.0的手机我还没用过，如果是视频播放不了，你可以看看我后面写的报错说明：

**Comment by Rukey7** [comment]
地址：http://www.jianshu.com/p/b1df2a42a380

**Comment by marren06** [comment]
群主的另外的开源视频库可以解决你的问题！ 我用了群主的视频播放的库！你去bilibili那去找答案 ijkplayer
