### ISSUE TITLE
导入AS报错请大佬指教。。。

### ISSUE THREAD

**Issue by ZJLeBron** [Rukey7/MvpApp#20]
Error:(1, 0) Cause: startup failed:
build file 'D:\360WiFi\2_20download\MvpApp-master\MvpApp-master\build.gradle': 1: Invalid variable name. Must start with a letter but was: ﻿
. At [1:1]  @ line 1, column 1.
   ﻿// Top-level build file where you can add configuration options common to all sub-projects/modules.
   ^

1 error

<a href="openFile:D:\360WiFi\2_20download\MvpApp-master\MvpApp-master\build.gradle">Open File</a>

**Comment by Rukey7** [comment]
这样我也看不出什么问题，你谷歌找找

**Comment by ZJLeBron** [comment]
应该是网络问题某些j依赖没有下载，一顿下载就ok了~

**Comment by Rukey7** [comment]
嗯，好的
