### ISSUE TITLE
这是一件艺术品

### ISSUE THREAD

**Issue by wangxuyang518** [Rukey7/MvpApp#21]
大佬，看了你这个项目。突然发现 你写的就是我一直苦苦追求的。。代码结构清晰，该有的注释都有。之前我一直是用mvc的。一个activity挤满了业务处理的逻辑。封装性，代码冗余更差。维护起来也不容易。都说现在android不好找工作。假如能有你这个技术，我找1.2w 绝对不成问题，更别说怕找不到工作。。。这样的代码功底，无论是android，还是java后台 还是其他的编程语言。。这样的代码风格 我给满分。看你这个项目 我找到自己今年的奋斗目标。真的是不能用语言来表达我对你的感激。给一个联系方式。我要拜师

**Comment by Rukey7** [comment]
额，你说得我都有点尴尬。你加我Q吧，363760359

**Comment by RaymanMartin** [comment]
同感觉是艺术品，准备在上班时间解通透这个项目。顺道把自己学过得Dagger2 RxJava Retrofit MVP 都巩固下，然而没想到。这里还加入了tinker，那时候做tinker搞了几天没下文了。
