### ISSUE TITLE
乐视手机好像没有适配，播放视频报错找不到libijkffmpeg.so，请大佬指教

### ISSUE THREAD

**Issue by ZJLeBron** [Rukey7/MvpApp#22]
/data/app/com.dl7.mvp-2/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]] couldn't find "libijkffmpeg.so"

**Comment by Rukey7** [comment]
看前面的，https://github.com/Rukey7/MvpApp/issues/6
