### ISSUE TITLE
大的bug:点击视频，app crash,并且无限重启

### ISSUE THREAD

**Issue by blank-space** [Rukey7/MvpApp#28]
机型 ：OnePlus 3T

**Comment by blank-space** [comment]
04-15 08:03:56.160 5340-5340/com.dl7.mvp W/System.err: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.dl7.mvp-1/base.apk"],nativeLibraryDirectories=[/data/app/com.dl7.mvp-1/lib/arm64, /data/app/com.dl7.mvp-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libijkffmpeg.so"

**Comment by Rukey7** [comment]
https://github.com/Rukey7/MvpApp/issues/6

**Comment by blank-space** [comment]
那无限重启的代码，你也有必要处理一下

**Comment by Rukey7** [comment]
异常的时候才会重启吧，我最近加了这个，你可以看下 CrashHandler 这个类

**Comment by 920651004** [comment]
重启那个这样解决在buildgradle中的defaultConfig中添加 ndk {
            abiFilters "armeabi", "armeabi-v7a", "x86", "mips"
        }并在gradle.properties中添加android.useDeprecatedNdk=true就可以了
