### ISSUE TITLE
viewpager 的滑动你怎么处理的

### ISSUE THREAD

**Issue by HenryHaoson** [Rukey7/MvpApp#32]
viewpager 的滑动你怎么处理的

**Comment by Rukey7** [comment]
滑动什么意思，我没明白

**Comment by HenryHaoson** [comment]
appbarlayout 和viewpager的滑动不会有冲突吗，我看你的很流畅，没有冲突，我自己写的会有冲突

**Comment by Rukey7** [comment]
不会啊，这个组合还是挺常见的，你要配合CoordinateLayout来使用，再给ViewPager加上app:layout_behavior="@string/appbar_scrolling_view_behavior" 属性

**Comment by HenryHaoson** [comment]
我错了，可能是跟recyclerview滑动冲突了

**Comment by Rukey7** [comment]
recyclerview用起来也一样
