### ISSUE TITLE
布局设置透明的话，会自动填充当前主题色？

### ISSUE THREAD

**Issue by codingWhenever** [Rukey7/MvpApp#38]
在布局文件中对控件设置透明度，直接被当前主题色覆盖了？

**Comment by Rukey7** [comment]
控件透明应该显示控件后面的其他窗口吧，你那边是什么问题

**Comment by codingWhenever** [comment]
对啊，理论效果应该是这样，但是我现在加入对一个线性布局设置带透明度的背景色，直接被当前项目的主题色填充？很纳闷啊，这个跟appTheme有关吗？

**Comment by Rukey7** [comment]
不会吧，你布局后面是什么

**Comment by codingWhenever** [comment]
我现在demo当前页面就是一个餐品列表，然后设置底边栏透明度，结果就是相当于在当前的主题色上进行透明度设置了，颜色明显不对啊，求解

**Comment by Rukey7** [comment]
加个QQ聊吧，这个关了，363760359
