### ISSUE TITLE
想问下非wifi下不加载图片是怎么实现的？谢谢

### ISSUE THREAD

**Issue by keeponZhang** [Rukey7/MvpApp#44]

**Comment by quert999** [comment]
/**  
 * make true current connect service is wifi  
 * @param mContext  
 * @return  
 */    
private static boolean isWifi(Context mContext) {    
    ConnectivityManager connectivityManager = (ConnectivityManager) mContext    
            .getSystemService(Context.CONNECTIVITY_SERVICE);    
    NetworkInfo activeNetInfo = connectivityManager.getActiveNetworkInfo();    
    if (activeNetInfo != null    
            && activeNetInfo.getType() == ConnectivityManager.TYPE_WIFI) {    
        return true;    
    }    
    return false;    
}   


随手百度的判断是否wifi连接，不是wifi环境下就不用glide加载图片就好。

**Comment by Rukey7** [comment]
就是这个意思
