### ISSUE TITLE
fail

### ISSUE THREAD

**Issue by dreamkong** [Rukey7/MvpApp#47]
Error:A problem occurred configuring root project 'MvpApp-master'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not find com.tencent.tinker:tinker-patch-gradle-plugin:1.7.7.
     Searched in the following locations:
         file:/Applications/Android Studio.app/Contents/gradle/m2repository/com/tencent/tinker/tinker-patch-gradle-plugin/1.7.7/tinker-patch-gradle-plugin-1.7.7.pom
         file:/Applications/Android Studio.app/Contents/gradle/m2repository/com/tencent/tinker/tinker-patch-gradle-plugin/1.7.7/tinker-patch-gradle-plugin-1.7.7.jar
         https://jcenter.bintray.com/com/tencent/tinker/tinker-patch-gradle-plugin/1.7.7/tinker-patch-gradle-plugin-1.7.7.pom
         https://jcenter.bintray.com/com/tencent/tinker/tinker-patch-gradle-plugin/1.7.7/tinker-patch-gradle-plugin-1.7.7.jar
         https://repo1.maven.org/maven2/com/tencent/tinker/tinker-patch-gradle-plugin/1.7.7/tinker-patch-gradle-plugin-1.7.7.pom
         https://repo1.maven.org/maven2/com/tencent/tinker/tinker-patch-gradle-plugin/1.7.7/tinker-patch-gradle-plugin-1.7.7.jar
     Required by:
         :MvpApp-master:unspecified

**Comment by Rukey7** [comment]
https://github.com/Tencent/tinker/issues/556
