### ISSUE TITLE
加载视图的bug

### ISSUE THREAD

**Issue by huang8023wei** [Rukey7/MvpApp#5]
出现网络错误时加载视图点击空白区域还能响应点击事件，    能进入recycle中的item中去 ，出现错误页面应该禁用item的点击事件

**Comment by Rukey7** [comment]
如果网络异常列表应该是加载不出来的，你能说下具体哪个界面，如果你还会出现这种情况，你可以试着在异常布局那里把点击事件消费掉

**Comment by huang8023wei** [comment]
在新闻栏目，我添加了一个家居，然后多次刷新后，就会出来网络请求错误页面，但是点击外面的区域还是能跳转，我看你用的framlayout布局，应该是显示的问题，其他页面多次刷新也会出现网络连接失败页面。但是有的页面点击空白区域不会跳转

**Comment by Rukey7** [comment]
没错没错，这个是我没处理好，我不该刷新还去更新加载界面，而应该刷新完再去处理，就算刷新失败也还是显示之前的界面。我重新加了个参数来处理刷新的方式，你可以看下
