### ISSUE TITLE
视频点进去报错

### ISSUE THREAD

**Issue by Mad-YX** [Rukey7/MvpApp#6]
catchexceptionwhenloadingtinker:java.lang.UnsatisfiedLinkError:dalvik.system.PathClassLoader[DexPathList[[zipfile"/data/app/com.dl7.mvp-1/base.apk"],nativeLibraryDirectories=[/data/app/com.dl7.mvp-1/lib/arm64,/data/app/com.dl7.mvp-1/base.apk!/lib/arm64-v8a,/vendor/lib64,/system/lib64]]]couldn'tfind"libijkffmpeg.so"
atjava.lang.Runtime.loadLibrary(Runtime.java:367)
atjava.lang.System.loadLibrary(System.java:1076)
attv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:163)
attv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:174)
atcom.dl7.player.media.IjkPlayerView._initMediaPlayer(IjkPlayerView.java:306)
atcom.dl7.player.media.IjkPlayerView.init(IjkPlayerView.java:464)
atcom.dl7.mvp.module.video.player.VideoPlayerActivity.initViews(VideoPlayerActivity.java:102)
atcom.dl7.mvp.module.base.BaseActivity.onCreate(BaseActivity.java:73)
atandroid.app.Activity.performCreate(Activity.java:6323)
atandroid.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
atandroid.app.ActivityThread.performLaunchActivity(ActivityThread.java:2385)
atandroid.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2492)
atandroid.app.ActivityThread.access$900(ActivityThread.java:153)
atandroid.app.ActivityThread$H.handleMessage(ActivityThread.java:1358)
atandroid.os.Handler.dispatchMessage(Handler.java:102)
atandroid.os.Looper.loop(Looper.java:148)
atandroid.app.ActivityThread.main(ActivityThread.java:5458)
atjava.lang.reflect.Method.invoke(NativeMethod)
atcom.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
atcom.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)

**Comment by Rukey7** [comment]
你看下这里的报错说明：http://www.jianshu.com/p/b1df2a42a380

**Comment by HelloCj** [comment]
我之前编译源码生成过ijkplayer.so，应该是支持大多数编码格式的，需要吗？

**Comment by Rukey7** [comment]
@HelloCj  看具体工作处理的业务需要什么格式来吧

**Comment by HelloCj** [comment]
@Rukey7 我觉得你说的对
