### ISSUE TITLE
导入报各种错，心累

### ISSUE THREAD

**Issue by Lee-Jian** [Rukey7/MvpApp#8]

**Comment by renchenglingge** [comment]
Error:(14, 0) Could not get unknown property 'TINKER_VERSION' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

**Comment by Rukey7** [comment]
嘿嘿，慢慢调一下，报错一般都是编译环境问题，这个在项目的gradle.properties里
![image](https://cloud.githubusercontent.com/assets/13436901/23653194/9f1f2cf4-0366-11e7-9e11-e26e1721025e.png)

**Comment by LxzBUG** [comment]
数了下  依赖34个 我也是很服气的
