### ISSUE TITLE
导入时tinker报错

### ISSUE THREAD

**Issue by renchenglingge** [Rukey7/MvpApp#9]
Error:(14, 0) Could not get unknown property 'TINKER_VERSION' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

classpath "com.tencent.tinker:tinker-patch-gradle-plugin:${TINKER_VERSION}"这句话

**Comment by Rukey7** [comment]
看[issues8](https://github.com/Rukey7/MvpApp/issues/8)
